// Mocks generated by Mockito 5.4.6 from annotations
// in com_palmcode_book/test/features/liked/data/repositories/liked_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:com_palmcode_book/features/book/domain/entities/book.dart'
    as _i4;
import 'package:com_palmcode_book/features/liked/data/datasources/local/liked_local_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LikedLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLikedLocalDataSource extends _i1.Mock
    implements _i2.LikedLocalDataSource {
  MockLikedLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Book>> getLikedBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getLikedBooks, []),
            returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
          )
          as _i3.Future<List<_i4.Book>>);

  @override
  _i3.Future<void> addLikedBook(_i4.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#addLikedBook, [book]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeLikedBook(int? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#removeLikedBook, [bookId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
