name: com_palmcode_book
description: A Flutter app for browsing books from Gutenberg API

version: 1.0.0+1


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  get_it: ^7.6.4
  flutter_svg: ^2.0.7
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mockito: ^5.4.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  # assets:
  #   - assets/